version: 3

phases:
  pre_build:
    commands:
      - npm install
      - npm run Docker-compose up 
  build:
    commands:
      - npm run test
  post_build:
    commands:
      - npm run Docker-compose down    

     